# Pull base image
FROM consol/tomcat-7.0:7.0.62-usermode

LABEL maintainer="rajusw804@gmail.com"

# Clean existing webapps if you want a clean deployment
RUN rm -rf /opt/tomcat/webapps/*

# Copy the artifact generated by the 'Build Maven Artifact' stage
COPY target/*.war /opt/tomcat/webapps/ROOT.war

# Optional: If your app needs a specific environment variable
# ENV JAVA_OPTS="-Xms512m -Xmx1024m"
